<template>
    <div class="mask w-screen flex flex-wrap">
      <p class="font-medium text-4xl text-white">
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;<span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Indétectable</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Caché</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Tourment</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Invisible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Imperceptible</span>&nbsp;
        <span class="transition-all duration-500 ease-in-out hover:text-bleu-999">Discret</span>&nbsp;

      </p>
    </div>
  </template>
  